name = "MolecularFingerprints"
uuid = "6289f4a8-86f2-4df5-b427-d4de5bbdeb05"
authors = ["Lukasz Sztukiewicz <lukasz.sztukiewicz@campus.tu-berlin.de>"]
version = "1.0.0-DEV"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
MolecularGraph = "6c89ec66-9cd8-5372-9f91-fabc50dd27fd"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
RDKitMinimalLib = "44044271-7623-48dc-8250-42433c44e4b7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
CSV = "0.10.15"
Graphs = "1.13.2"
MolecularGraph = "0.21.1"
PythonCall = "0.9.31"
RDKitMinimalLib = "1.2.0"
Random = "1.11.0"
ReferenceTests = "0.10"
SHA = "0.7.0"
SparseArrays = "1.11.0"
Test = "1.11.0"
julia = "1.11"

[extras]
ReferenceTests = "324d217c-45ce-50fc-942e-d289b448e8cf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "ReferenceTests"]
