name = "MolecularFingerprints"
uuid = "6289f4a8-86f2-4df5-b427-d4de5bbdeb05"
authors = ["Lukasz Sztukiewicz <lukasz.sztukiewicz@campus.tu-berlin.de>"]
version = "1.1.0"

[deps]
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
MolecularGraph = "6c89ec66-9cd8-5372-9f91-fabc50dd27fd"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
RDKitMinimalLib = "44044271-7623-48dc-8250-42433c44e4b7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
Graphs = "1.13.2"
MolecularGraph = "0.21.1"
PythonCall = "0.9.31"
RDKitMinimalLib = "1.2.0"
Random = "1.11.0"
SHA = "0.7.0"
SparseArrays = "1.11.0"
julia = "1.11"