name = "MolecularFingerprints"
uuid = "6289f4a8-86f2-4df5-b427-d4de5bbdeb05"
authors = ["Lukasz Sztukiewicz <lukasz.sztukiewicz@campus.tu-berlin.de>"]
version = "1.0.0-DEV"

[deps]
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
MolecularGraph = "6c89ec66-9cd8-5372-9f91-fabc50dd27fd"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
Graphs = "1.13.2"
MolecularGraph = "0.21.1"
Random = "1.11.0"
julia = "1.11"
